// Generated by CoffeeScript 1.7.1
(function(WIN, DOC) {
  var $, el, elBtns, noop, querySelectorAll, text, _i, _len, _results;
  noop = function() {};
  querySelectorAll = DOC["querySelectorAll"];
  $ = noop.bind ? querySelectorAll.bind(DOC) : function(selector) {
    return querySelectorAll(selector);
  };
  elBtns = $(".btn");
  _results = [];
  for (_i = 0, _len = elBtns.length; _i < _len; _i++) {
    el = elBtns[_i];
    text = el.innerHTML;
    _results.push(el.innerHTML = "<b>" + text + "</b><u class='ui-loading'></u>");
  }
  return _results;
})(window, document);
