// Generated by CoffeeScript 1.7.1
(function(WIN, DOC) {
  var $, el, elBtns, setELe, _i, _len, _results;
  $ = function(selector) {
    return DOC["querySelectorAll"](selector);
  };
  elBtns = $(".btn");
  setELe = function(el) {
    var text;
    text = el.innerHTML;
    return el.innerHTML = "<b>" + text + "</b><u class='ui-loading'></u>";
  };
  _results = [];
  for (_i = 0, _len = elBtns.length; _i < _len; _i++) {
    el = elBtns[_i];
    _results.push(setELe(el));
  }
  return _results;
})(window, document);
